#!/bin/bash

spinner() {
    local i sp n
    sp='/-\|'
    n=${#sp}
    printf ' '
    while sleep 0.1; do
        printf "%s\b${sp:i++%n:1}"
    done
}

echo 'Automatically fixing code with PHPCodeSniffer (WordPress-Core)'
spinner &

tests/vendor/bin/phpcbf --standard=WordPress-Core --extensions=php --severity=1 admin/docupress-article-ratings.php > tests/phpcbf.txt
code tests/phpcbf.txt

kill "$!" # kill the spinner
printf '%s\b'

echo 'Code sniffing completed!'